name: Sync to Hugging Face hub-learning

on:
  push:
    branches: [learning_agent]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push learning_agent branch to HuggingFace main
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://ImashaNawodi:$HF_TOKEN@huggingface.co/spaces/ImashaNawodi/learning_Agent
          
          # Force push GitHub's learning_agent → HuggingFace main
          git push hf learning_agent:main --force
